# Generated by Django 5.2.8 on 2026-01-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_section", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="mobile",
        ),
    ]
