# Generated by Django 5.2.8 on 2026-01-19 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_color_hex_code"),
        ("user_section", "0002_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="products.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="user_section.wishlist",
            ),
        ),
    ]
