# Generated by Django 5.2.8 on 2026-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_section", "0003_alter_wishlistitem_variant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("order", "Order Inquiry"),
                            ("product", "Product Question"),
                            ("shipping", "Shipping & Returns"),
                            ("technical", "Technical Support"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
        ),
    ]
