# Generated by Django 5.2.8 on 2026-03-05 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offer", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="product",
            field=models.ManyToManyField(
                blank=True, related_name="product_offers", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralusage",
            name="receiver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralusage",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                fields=("user", "coupon"), name="unique_user_coupon"
            ),
        ),
    ]
