# Generated by Django 5.2.8 on 2026-02-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brandsandcategories",
            "0007_remove_brand_description_remove_category_description",
        ),
        ("offer", "0001_initial"),
        ("products", "0013_alter_productvariantimage_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offer",
            name="unique_offer_per_target",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="target_type",
            new_name="offer_type",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="target_id",
        ),
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_offers",
                to="brandsandcategories.category",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_offers",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
