# Generated by Django 5.2.8 on 2026-02-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_remove_offer_unique_offer_per_target_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="discount_value",
        ),
        migrations.AddField(
            model_name="offer",
            name="discount_percentage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
