# Generated by Django 5.2.8 on 2026-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brandsandcategories",
            "0007_remove_brand_description_remove_category_description",
        ),
        ("offer", "0003_remove_offer_discount_type_and_more"),
        ("products", "0013_alter_productvariantimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="product",
        ),
        migrations.AddField(
            model_name="offer",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="category_offers",
                to="brandsandcategories.category",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="product",
            field=models.ManyToManyField(
                blank=True, related_name="product_offers", to="products.product"
            ),
        ),
    ]
