# Generated by Django 5.2.8 on 2026-02-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0005_referral_referralusage_wallet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
