# Generated by Django 5.2.8 on 2026-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0006_delete_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "receiver_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="referralusage",
            name="receiver_reward_points",
        ),
        migrations.RemoveField(
            model_name="referralusage",
            name="referrer_reward_points",
        ),
        migrations.AddField(
            model_name="referralusage",
            name="receiver_reward_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="referralusage",
            name="referrer_reward_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
