# Generated by Django 5.2.8 on 2026-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0008_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
