# Generated by Django 5.2.8 on 2026-02-13 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0010_coupon_max_usage_per_user_couponusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="couponusage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="limit",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                fields=("user", "coupon"), name="unique_user_coupon"
            ),
        ),
    ]
