# Generated by Django 5.2.8 on 2025-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
