# Generated by Django 5.2.8 on 2025-12-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="created_at",
            new_name="date_joined",
        ),
    ]
