# Generated by Django 5.2.8 on 2026-01-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_pic",
        ),
    ]
