# Generated by Django 5.2.8 on 2026-01-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_customuser_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
