# Generated by Django 5.2.8 on 2026-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_used_referral",
            field=models.BooleanField(default=False),
        ),
    ]
