# Generated by Django 5.2.8 on 2026-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_has_used_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_seen_referral_page",
            field=models.BooleanField(default=False),
        ),
    ]
