# Generated by Django 5.2.8 on 2026-02-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_customuser_referral_code_customuser_referred_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="referred_by",
        ),
    ]
