# Generated by Django 5.2.8 on 2026-02-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_customuser_has_seen_referral_page"),
        ("accounts", "0013_remove_customuser_referral_code_and_more"),
    ]

    operations = []
