# Generated by Django 5.2.8 on 2026-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallet",
            "0002_alter_wallettransaction_options_remove_wallet_points_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdrawal"),
                    ("REFERRAL", "Referral Reward"),
                ],
                max_length=10,
            ),
        ),
    ]
