# Generated by Django 5.2.8 on 2026-02-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("PAYMENT", "Order Payment"),
                    ("REFERRAL", "Referral Reward"),
                    ("REFUND", "Refund"),
                ],
                max_length=10,
            ),
        ),
    ]
