# Generated by Django 5.2.8 on 2026-01-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_wishlist"),
        ("products", "0011_color_hex_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="added_at",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productvariant",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.wishlist"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="variant",
        ),
    ]
