# Generated by Django 5.2.8 on 2026-01-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_rename_added_at_wishlist_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistitem",
            name="wishlist",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="variant",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
