# Generated by Django 5.2.8 on 2026-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cart_unique_active_cart_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
