# Generated by Django 5.2.8 on 2026-02-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cartitem_base_price_cartitem_final_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="final_price",
        ),
    ]
