# Generated by Django 5.2.8 on 2026-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("razorpay", "Razorpay"),
                    ("wallet", "Wallet"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                    ("failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
