# Generated by Django 5.2.8 on 2026-01-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_cancelled_at_order_delivered_at_and_more"),
        ("user_section", "0003_alter_wishlistitem_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="user_section.useraddress",
            ),
        ),
    ]
