# Generated by Django 5.2.8 on 2026-01-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_address"),
        ("user_section", "0003_alter_wishlistitem_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_orders",
                to="user_section.useraddress",
            ),
        ),
    ]
