# Generated by Django 5.2.8 on 2026-01-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="cancelled",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="returned",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("none", "No Return"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("return_completed", "Return Completed"),
                    ("return_canceled", "Return Cancelled"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
