# Generated by Django 5.2.8 on 2026-01-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_billing_address"),
        ("user_section", "0003_alter_wishlistitem_variant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_section.useraddress",
            ),
        ),
    ]
