# Generated by Django 5.2.8 on 2026-01-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_remove_orderitem_cancelled_remove_orderitem_returned_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("none", "No Return"),
                    ("return_requested", "Return Requested"),
                    ("return_approved", "Return Approved"),
                    ("return_rejected", "Return Rejected"),
                    ("returned", "Returned"),
                    ("return_canceled", "Return Cancelled"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
