# Generated by Django 5.2.8 on 2026-02-16 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0011_alter_couponusage_unique_together_alter_coupon_limit_and_more"),
        ("orders", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="offer.coupon",
            ),
        ),
    ]
