# Generated by Django 5.2.8 on 2026-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
