# Generated by Django 5.2.8 on 2026-02-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_coupon_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon_discount",
        ),
    ]
