# Generated by Django 5.2.8 on 2026-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_remove_order_coupon_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
