# Generated by Django 5.2.8 on 2026-01-06 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brandsandcategories",
            "0003_alter_category_options_alter_category_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="categories/images/default_category.png",
                upload_to="categories/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
