# Generated by Django 5.2.8 on 2026-01-14 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandsandcategories", "0005_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="brands/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "svg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
