# Generated by Django 5.2.8 on 2026-01-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "brandsandcategories",
            "0006_remove_category_image_alter_brand_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
