# Generated by Django 5.2.8 on 2025-12-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "brandsandcategories",
            "0002_alter_brand_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/images"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the category",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_selective", models.BooleanField(default=False)),
                ("is_most_demanded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="brandsandcategories.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="brandsandcategories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="products_pr_categor_50f5f1_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="products_pr_is_feat_a5d7cd_idx"
                    ),
                    models.Index(
                        fields=["is_most_demanded"],
                        name="products_pr_is_most_4946c4_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="products_pr_created_bce1a7_idx"
                    ),
                    models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
                ],
            },
        ),
    ]
