# Generated by Django 5.2.8 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_alt_text_remove_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Current inventory count"
            ),
        ),
    ]
