# Generated by Django 5.2.8 on 2026-01-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_color_size_remove_product_base_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
