# Generated by Django 5.2.8 on 2026-01-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_image_productvariantimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantimage",
            name="is_primary",
            field=models.BooleanField(default=True),
        ),
    ]
