# Generated by Django 5.2.8 on 2026-01-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvariantimage_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
