# Generated by Django 5.2.8 on 2026-01-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productvariantimage_is_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
