# Generated by Django 5.2.8 on 2026-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_productvariant_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="hex_code",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
