# Generated by Django 5.2.8 on 2026-01-19 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_color_hex_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariantimage",
            name="image",
            field=models.ImageField(
                upload_to="variant-images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
