# Generated by Django 5.2.8 on 2026-02-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productvariantimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="offer_price",
            new_name="sales_price",
        ),
    ]
