# Generated by Django 5.2.8 on 2026-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="size",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
