# Generated by Django 5.2.8 on 2026-02-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_alter_size_options_size_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={},
        ),
        migrations.RemoveField(
            model_name="size",
            name="order",
        ),
    ]
