# Generated by Django 5.2.8 on 2026-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_size_options_remove_size_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auto_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
