# Generated by Django 5.2.8 on 2026-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_auto_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
